adminUser:
  password: vault:pr-112-16-boot-gke/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-112-16-boot-gke/pipelineUser:token
  username: cjxd-bot-test
prow:
  hmacToken: vault:pr-112-16-boot-gke/prow:hmacToken
